"""
Read chopper — split reads at internal adapter junctions.

Takes the junction sites detected by AdapterFinder and produces
rescued sub-reads as independent FASTQ records.  Short fragments
below a configurable threshold are discarded.

Output naming convention::

    Original:  read_001
    Chopped:   read_001_part1, read_001_part2, ...
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional, Set, Tuple

from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

from directclean.rescuer.adaptor_seq import AdapterConfig
from directclean.rescuer.adapter_finder import (
    AdapterFinder,
    FinderResult,
    InternalJunction,
)
from directclean.utils.io import read_fastq, write_fastq

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

@dataclass
class RescueReport:
    """Summary statistics for the rescue operation.

    Attributes:
        total_reads:        Total reads processed from input FASTQ.
        reads_with_internal: Reads that had ≥1 internal junction.
        reads_without:       Reads passed through unchanged.
        total_segments:     Total sub-reads written (includes unchanged
                            reads + rescued segments).
        segments_rescued:   Sub-reads generated by chopping.
        segments_discarded: Sub-reads too short and discarded.
        details:            Per-read FinderResult for reporting.
    """
    total_reads: int = 0
    reads_with_internal: int = 0
    reads_without: int = 0
    total_segments: int = 0
    segments_rescued: int = 0
    segments_discarded: int = 0
    details: List[FinderResult] = field(default_factory=list, repr=False)

    def __str__(self) -> str:
        pct = (
            f"{self.reads_with_internal / self.total_reads * 100:.1f}%"
            if self.total_reads > 0 else "N/A"
        )
        return (
            "=== DirectClean Rescue Report ===\n"
            f"  Total reads processed   : {self.total_reads:,}\n"
            f"  Reads with internal adpt: {self.reads_with_internal:,} ({pct})\n"
            f"  Reads passed unchanged  : {self.reads_without:,}\n"
            f"  ---\n"
            f"  Segments rescued        : {self.segments_rescued:,}\n"
            f"  Segments discarded      : {self.segments_discarded:,}\n"
            f"  Total output reads      : {self.total_segments:,}\n"
            "================================="
        )


# ---------------------------------------------------------------------------
# Chopper
# ---------------------------------------------------------------------------

def _chop_record(
    record: SeqRecord,
    junctions: List[InternalJunction],
    min_segment_length: int,
) -> Tuple[List[SeqRecord], int]:
    """Split a SeqRecord at the given chop positions.

    Each resulting segment inherits the original read's quality scores
    for its portion of the sequence.

    Args:
        record:             Original FASTQ record.
        junctions:          Sorted list of junctions with chop positions.
        min_segment_length: Minimum bp to keep a segment.

    Returns:
        (kept_segments, discarded_count)
    """
    seq = str(record.seq)
    quals = record.letter_annotations.get("phred_quality", [])
    read_id = record.id

    # Build list of chop boundaries: [0, chop1, chop2, ..., read_len]
    boundaries = [0]
    for junc in junctions:
        boundaries.append(junc.chop_position)
    boundaries.append(len(seq))

    segments: List[SeqRecord] = []
    discarded = 0

    for i in range(len(boundaries) - 1):
        start = boundaries[i]
        end = boundaries[i + 1]
        seg_len = end - start

        if seg_len < min_segment_length:
            discarded += 1
            continue

        seg_seq = seq[start:end]
        seg_id = f"{read_id}_part{i + 1}"

        seg_record = SeqRecord(
            seq=Seq(seg_seq),
            id=seg_id,
            name=seg_id,
            description=f"rescued_from={read_id} start={start} end={end}",
        )

        # Preserve quality scores if available
        if quals:
            seg_record.letter_annotations["phred_quality"] = quals[start:end]

        segments.append(seg_record)

    return segments, discarded


class ReadChopper:
    """Chop reads at internal adapter junctions and write rescued FASTQ.

    Combines AdapterFinder (detection) with chopping logic and FASTQ
    I/O into a single entry point.

    Usage::

        chopper = ReadChopper(
            input_fastq="restranded.fastq",
            output_fastq="rescued.fastq",
        )
        report = chopper.run()
        print(report)

    Args:
        input_fastq:   Path to input FASTQ (from Restrander).
        output_fastq:  Path for output FASTQ with rescued reads.
        config:        AdapterConfig with detection parameters.
        min_confidence: Minimum confidence level to chop (1, 2, or 3).
                        Default 2 means polyA-only hits are ignored.
        report_path:   Optional path for a per-read TSV report.
    """

    def __init__(
        self,
        input_fastq: str | Path,
        output_fastq: str | Path,
        config: AdapterConfig | None = None,
        min_confidence: int = 2,
        report_path: Optional[str | Path] = None,
    ) -> None:
        self.input_fastq = Path(input_fastq)
        self.output_fastq = Path(output_fastq)
        self.config = config or AdapterConfig()
        self.min_confidence = min_confidence
        self.report_path = Path(report_path) if report_path else None

        self.finder = AdapterFinder(self.config)

        # Ensure output directory exists
        self.output_fastq.parent.mkdir(parents=True, exist_ok=True)

    def run(self) -> RescueReport:
        """Process the entire FASTQ and write rescued output.

        Returns:
            RescueReport with statistics.
        """
        report = RescueReport()
        all_output_records: List[SeqRecord] = []

        for record in read_fastq(self.input_fastq):
            report.total_reads += 1
            sequence = str(record.seq)

            # Detect internal adapters
            finder_result = self.finder.find(
                read_id=record.id,
                sequence=sequence,
            )

            # Filter junctions by confidence
            qualified = [
                j for j in finder_result.junctions
                if j.confidence >= self.min_confidence
            ]

            if not qualified:
                # No internal adapter — pass through unchanged
                report.reads_without += 1
                report.total_segments += 1
                all_output_records.append(record)
            else:
                # Chop the read
                report.reads_with_internal += 1
                report.details.append(finder_result)

                segments, discarded = _chop_record(
                    record, qualified, self.config.min_segment_length
                )

                report.segments_rescued += len(segments)
                report.segments_discarded += discarded
                report.total_segments += len(segments)
                all_output_records.extend(segments)

        # Write output
        write_fastq(all_output_records, self.output_fastq)

        # Write optional report
        if self.report_path is not None:
            self._write_report(report)

        logger.info("Rescue complete.")
        logger.info(f"\n{report}")
        return report

    def _write_report(self, report: RescueReport) -> None:
        """Write a per-read TSV report."""
        self.report_path.parent.mkdir(parents=True, exist_ok=True)

        with open(self.report_path, "w") as fh:
            fh.write(
                "read_id\tn_junctions\tconfidences\tchop_positions\tdetails\n"
            )

            for fr in report.details:
                confidences = ",".join(
                    str(j.confidence) for j in fr.junctions
                )
                positions = ",".join(
                    str(j.chop_position) for j in fr.junctions
                )

                detail_parts = []
                for j in fr.junctions:
                    parts = []
                    if j.polya_hit:
                        parts.append(
                            f"polyA[{j.polya_hit.start}-{j.polya_hit.end}]"
                        )
                    if j.rtp_rc_hit:
                        parts.append(
                            f"RTP_rc[{j.rtp_rc_hit.start}-{j.rtp_rc_hit.end}]"
                            f"(ed={j.rtp_rc_hit.edit_distance})"
                        )
                    if j.tso_hit:
                        parts.append(
                            f"TSO[{j.tso_hit.start}-{j.tso_hit.end}]"
                            f"(ed={j.tso_hit.edit_distance})"
                        )
                    detail_parts.append("+".join(parts))

                fh.write(
                    f"{fr.read_id}\t{fr.n_chops}\t{confidences}\t"
                    f"{positions}\t{';'.join(detail_parts)}\n"
                )