"""
Artifact classifier — main orchestrator for the homopolymer filter.

Reads a BAM file, identifies chimeric reads whose inter-segment
junctions show homopolymer-mediated RT template switching, then
**chops** artifact reads at those junctions to rescue the flanking
sub-reads instead of discarding the entire read.

Changed in v2.0:
    Previously, artifact reads were removed entirely.  Now, artifact
    junctions are treated as chop points — analogous to Stage 3's
    internal-adapter rescue — so that valid gene segments on either
    side of a homopolymer junction are preserved as independent reads.

Typical usage::

    classifier = ArtifactClassifier(
        bam_path="aligned.bam",
        input_fastq="rescued.fastq",
        output_dir="results/",
    )
    report = classifier.run()
    print(report)
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

from directclean.filter.junction_parser import iter_chimeric_reads, ChimericRead
from directclean.filter.homopolymer import (
    HomopolymerConfig,
    HomopolymerDetector,
    ReadVerdict,
)
from directclean.utils.io import read_fastq, write_fastq

logger = logging.getLogger(__name__)

# Minimum sub-read length to keep after chopping (bp)
_MIN_SEGMENT_LENGTH = 100


# ---------------------------------------------------------------------------
# Report data class
# ---------------------------------------------------------------------------

@dataclass
class FilterReport:
    """Summary statistics produced after homopolymer rescue.

    Attributes:
        total_chimeric_reads:   Reads with SA tag (candidates examined).
        artifact_reads:         Reads with ≥1 homopolymer artifact junction.
        clean_chimeric_reads:   Chimeric reads that passed the filter.
        total_junctions:        Total inter-segment junctions examined.
        artifact_junctions:     Junctions that triggered the filter.
        total_reads_in_fastq:   Reads in the input FASTQ (chimeric + non-chimeric).
        output_reads:           Total reads written to cleaned output
                                (passthrough + rescued sub-reads).
        segments_rescued:       Sub-reads generated by chopping artifacts.
        segments_discarded:     Sub-reads too short (<100 bp) and discarded.
    """
    total_chimeric_reads: int = 0
    artifact_reads: int = 0
    clean_chimeric_reads: int = 0
    total_junctions: int = 0
    artifact_junctions: int = 0
    total_reads_in_fastq: int = 0
    output_reads: int = 0
    segments_rescued: int = 0
    segments_discarded: int = 0
    verdicts: List[ReadVerdict] = field(default_factory=list, repr=False)

    # Keep old attribute names accessible for backward compatibility
    @property
    def kept_reads(self) -> int:
        return self.output_reads

    @property
    def removed_reads(self) -> int:
        return 0  # No reads are removed in rescue mode

    def __str__(self) -> str:
        pct = (
            f"{self.artifact_reads / self.total_chimeric_reads * 100:.1f}%"
            if self.total_chimeric_reads > 0 else "N/A"
        )
        return (
            "=== DirectClean Homopolymer Rescue Report ===\n"
            f"  Chimeric reads examined : {self.total_chimeric_reads:,}\n"
            f"  Artifact reads (chopped): {self.artifact_reads:,} ({pct})\n"
            f"  Clean chimeric reads    : {self.clean_chimeric_reads:,}\n"
            f"  Total junctions         : {self.total_junctions:,}\n"
            f"  Artifact junctions      : {self.artifact_junctions:,}\n"
            f"  ---\n"
            f"  Input FASTQ reads       : {self.total_reads_in_fastq:,}\n"
            f"  Segments rescued        : {self.segments_rescued:,}\n"
            f"  Segments discarded (<{_MIN_SEGMENT_LENGTH}bp): {self.segments_discarded:,}\n"
            f"  Output reads            : {self.output_reads:,}\n"
            "=============================================="
        )


# ---------------------------------------------------------------------------
# Classifier
# ---------------------------------------------------------------------------

class ArtifactClassifier:
    """End-to-end homopolymer artifact rescue.

    Workflow:
        1. Iterate over chimeric reads in the BAM.
        2. For each read, extract junctions and run the homopolymer
           detector on the flanking sequences.
        3. Collect artifact read IDs and their chop positions
           (read-coordinate positions of artifact junctions).
        4. Stream through the original FASTQ: pass clean reads through
           unchanged, chop artifact reads at junction positions and
           write rescued sub-reads (≥100 bp) to output.

    Args:
        bam_path:      Path to minimap2 BAM (sorted & indexed).
        input_fastq:   Original FASTQ that was aligned.
        output_dir:    Directory for output files.
        config:        HomopolymerConfig with detection parameters.
        context_window: Bases to extract on each side of a junction
                        (passed to junction_parser).
        min_mapq:      Minimum mapping quality for a segment to be
                        considered.
        prefix:        Filename prefix for outputs (default "directclean").
        min_segment_length: Minimum sub-read length to keep after
                        chopping (default 100 bp).
    """

    def __init__(
        self,
        bam_path: str | Path,
        input_fastq: str | Path,
        output_dir: str | Path,
        config: HomopolymerConfig | None = None,
        context_window: int = 30,
        min_mapq: int = 0,
        prefix: str = "directclean",
        min_segment_length: int = _MIN_SEGMENT_LENGTH,
    ) -> None:
        self.bam_path = str(bam_path)
        self.input_fastq = Path(input_fastq)
        self.output_dir = Path(output_dir)
        self.context_window = context_window
        self.min_mapq = min_mapq
        self.prefix = prefix
        self.min_segment_length = min_segment_length

        self.config = config or HomopolymerConfig()
        self.detector = HomopolymerDetector(self.config)

        # Ensure output directory exists
        self.output_dir.mkdir(parents=True, exist_ok=True)

    # ---- output paths ----

    @property
    def cleaned_fastq(self) -> Path:
        return self.output_dir / f"{self.prefix}.cleaned.fastq"

    @property
    def rescued_fastq(self) -> Path:
        """FASTQ containing sub-reads rescued from artifact reads."""
        return self.output_dir / f"{self.prefix}.rescued.fastq"

    @property
    def report_path(self) -> Path:
        return self.output_dir / f"{self.prefix}.homopolymer_report.tsv"

    # ---- Phase 1: scan BAM ----

    def scan_bam(self) -> Tuple[Dict[str, List[int]], FilterReport]:
        """Scan BAM for chimeric reads and classify junctions.

        Returns:
            (chop_map, report) — dict mapping artifact read IDs to
            sorted list of chop positions (read coordinates), and
            a partially filled FilterReport.
        """
        logger.info("Phase 1: scanning BAM for homopolymer artifacts ...")

        # Map: read_id -> sorted list of artifact junction positions
        chop_map: Dict[str, List[int]] = {}
        report = FilterReport()

        for chimeric in iter_chimeric_reads(
            self.bam_path,
            window_size=self.context_window,
            min_mapq=self.min_mapq,
        ):
            report.total_chimeric_reads += 1
            verdict = self.detector.judge_read(chimeric)
            report.verdicts.append(verdict)
            report.total_junctions += verdict.n_junctions
            report.artifact_junctions += verdict.n_artifact_junctions

            if verdict.is_artifact:
                report.artifact_reads += 1
                # Collect read-coordinate positions of artifact junctions
                artifact_positions = [
                    jv.junction.read_position
                    for jv in verdict.junction_verdicts
                    if jv.is_artifact
                ]
                artifact_positions.sort()
                chop_map[verdict.read_id] = artifact_positions

        report.clean_chimeric_reads = (
            report.total_chimeric_reads - report.artifact_reads
        )

        logger.info(
            f"BAM scan complete: {report.total_chimeric_reads:,} chimeric reads, "
            f"{report.artifact_reads:,} artifacts to rescue"
        )
        return chop_map, report

    # ---- Phase 2: chop and write FASTQ ----

    @staticmethod
    def _chop_read(
        record: SeqRecord,
        chop_positions: List[int],
        min_segment_length: int,
    ) -> Tuple[List[SeqRecord], int]:
        """Split a SeqRecord at the given chop positions.

        Each resulting sub-read inherits the original read's quality
        scores for its portion of the sequence.  Sub-reads shorter
        than min_segment_length are discarded.

        Naming follows Stage 3 convention:
            original_id_part1, original_id_part2, ...

        Args:
            record:             Original FASTQ record.
            chop_positions:     Sorted list of read-coordinate positions
                                where artifact junctions occur.
            min_segment_length: Minimum bp to keep a sub-read.

        Returns:
            (kept_segments, discarded_count)
        """
        seq = str(record.seq)
        quals = record.letter_annotations.get("phred_quality", [])
        read_id = record.id

        # Build boundaries: [0, chop1, chop2, ..., read_len]
        boundaries = [0]
        for pos in chop_positions:
            # Avoid duplicates or out-of-range positions
            if 0 < pos < len(seq) and pos != boundaries[-1]:
                boundaries.append(pos)
        boundaries.append(len(seq))

        segments: List[SeqRecord] = []
        discarded = 0

        for i in range(len(boundaries) - 1):
            start = boundaries[i]
            end = boundaries[i + 1]
            seg_len = end - start

            if seg_len < min_segment_length:
                discarded += 1
                continue

            seg_seq = seq[start:end]
            seg_id = f"{read_id}_hppart{i + 1}"

            seg_record = SeqRecord(
                seq=Seq(seg_seq),
                id=seg_id,
                name=seg_id,
                description=(
                    f"homopolymer_rescued_from={read_id} "
                    f"start={start} end={end}"
                ),
            )

            # Preserve quality scores if available
            if quals:
                seg_record.letter_annotations["phred_quality"] = quals[start:end]

            segments.append(seg_record)

        return segments, discarded

    def rescue_fastq(
        self,
        chop_map: Dict[str, List[int]],
        report: FilterReport,
    ) -> FilterReport:
        """Stream FASTQ: pass clean reads, chop artifact reads.

        Clean reads (not in chop_map) go to cleaned.fastq unchanged.
        Artifact reads are chopped at junction positions; rescued
        sub-reads (≥ min_segment_length) also go to cleaned.fastq.
        A separate rescued.fastq contains only the chopped sub-reads
        for bookkeeping.

        Args:
            chop_map: Read ID -> sorted artifact junction positions.
            report:   FilterReport to fill with output counts.

        Returns:
            Updated FilterReport.
        """
        logger.info("Phase 2: rescue-chopping artifact reads ...")

        cleaned_path = self.cleaned_fastq
        rescued_path = self.rescued_fastq
        cleaned_path.parent.mkdir(parents=True, exist_ok=True)
        rescued_path.parent.mkdir(parents=True, exist_ok=True)

        total_input = 0
        total_output = 0
        total_rescued = 0
        total_discarded = 0

        with open(cleaned_path, "w") as f_cleaned, \
             open(rescued_path, "w") as f_rescued:

            from Bio import SeqIO as _SeqIO

            for record in read_fastq(self.input_fastq):
                total_input += 1

                if record.id in chop_map:
                    # Artifact read: chop at junction positions
                    chop_positions = chop_map[record.id]
                    segments, discarded = self._chop_read(
                        record, chop_positions, self.min_segment_length,
                    )
                    total_rescued += len(segments)
                    total_discarded += discarded
                    total_output += len(segments)

                    for seg in segments:
                        _SeqIO.write(seg, f_cleaned, "fastq")
                        _SeqIO.write(seg, f_rescued, "fastq")
                else:
                    # Clean read: pass through unchanged
                    _SeqIO.write(record, f_cleaned, "fastq")
                    total_output += 1

        report.total_reads_in_fastq = total_input
        report.output_reads = total_output
        report.segments_rescued = total_rescued
        report.segments_discarded = total_discarded

        logger.info(
            f"Rescue complete: {total_input:,} input reads → "
            f"{total_output:,} output reads "
            f"({total_rescued:,} rescued, {total_discarded:,} discarded)"
        )
        return report

    # ---- Phase 3: write TSV report ----

    def write_report(self, report: FilterReport) -> None:
        """Write a per-read TSV report for downstream inspection.

        Columns: read_id, verdict, n_junctions, n_artifact_junctions,
                 junction_details (semicolon-separated).

        The verdict column now uses RESCUED instead of ARTIFACT for
        reads that were chopped rather than removed.
        """
        logger.info(f"Writing report to {self.report_path}")

        with open(self.report_path, "w") as fh:
            header = (
                "read_id\tverdict\tn_junctions\tn_artifact_junctions"
                "\tjunction_details\n"
            )
            fh.write(header)

            for rv in report.verdicts:
                details_parts = []
                for jv in rv.junction_verdicts:
                    left = jv.junction.left_segment
                    right = jv.junction.right_segment
                    detail = (
                        f"{left.chrom}:{left.ref_start}({left.strand})->"
                        f"{right.chrom}:{right.ref_start}({right.strand})"
                        f"|pos={jv.junction.read_position}"
                        f"|up_hit={jv.upstream_hit.is_hit}"
                        f"(d={jv.upstream_hit.density:.2f},"
                        f"run={jv.upstream_hit.longest_run_length})"
                        f"|dn_hit={jv.downstream_hit.is_hit}"
                        f"(d={jv.downstream_hit.density:.2f},"
                        f"run={jv.downstream_hit.longest_run_length})"
                        f"|artifact={jv.is_artifact}"
                    )
                    details_parts.append(detail)

                line = (
                    f"{rv.read_id}\t"
                    f"{'RESCUED' if rv.is_artifact else 'CLEAN'}\t"
                    f"{rv.n_junctions}\t"
                    f"{rv.n_artifact_junctions}\t"
                    f"{';'.join(details_parts)}\n"
                )
                fh.write(line)

    # ---- Public entry point ----

    def run(self) -> FilterReport:
        """Execute the full homopolymer rescue pipeline.

        Returns:
            FilterReport with all statistics.
        """
        chop_map, report = self.scan_bam()
        report = self.rescue_fastq(chop_map, report)
        self.write_report(report)

        logger.info("Homopolymer rescue complete.")
        logger.info(f"\n{report}")
        return report
